In this example, we use CellCnn to analyze a mass cytometry dataset acquired to characterize human natural killer (NK) cell diversity and associate NK cell subsets with genetic and environmental factors, namely prior Cytomegalovirus (CMV) infection [1]. This dataset comprises mass cytometry measurements of 36 markers, including 28 NK cell receptors, for PBMC samples of 20 donors with varying serology for CMV. 

We will train CellCnn to identify CMV seropositivity-associated cell populations from the **ungated data** (after removal of dead cells and doublets). To run this example, please download the [NK cell dataset](http://www.imsb.ethz.ch/research/claassen/Software/cellcnn.html) and place the decompressed folder in the cellCnn/examples directory.

[1] Horowitz, A. et al. Genetic and environmental determinants of human NK cell diversity revealed by mass cytometry. Sci. Transl. Med. 5 (2013).

In [6]:
import os, sys, errno, glob, fcm
import numpy as np

import cellCnn
from cellCnn.utils import ftrans, mkdir_p, get_items
from cellCnn.model import CellCnn
from cellCnn.plotting import plot_results_2class
from sklearn.metrics import *

%pylab inline


Using Theano backend.


Populating the interactive namespace from numpy and matplotlib


In [14]:
# define input and output directories
WDIR = os.path.join(cellCnn.__path__[0], 'examples')
FCS_DATA_PATH = os.path.join(WDIR, 'NK_cell_dataset', 'gated_alive')

# define output directory
OUTDIR = os.path.join(WDIR, 'output_NK_ungated')
mkdir_p(OUTDIR)

In [15]:
# look at the measured markers
data_fcs = fcm.loadFCS(glob.glob(FCS_DATA_PATH + '/*.fcs')[0], transform=None, auto_comp=False)
print data_fcs.channels


['Time', 'Cell_length', 'CD3', 'Dead', '(La139)Dd', 'CD27', 'CD19', 'CD4', 'CD8', 'CD57', '2DL1-S1', 'TRAIL', '2DL2-L3-S2', 'CD16', 'CD10', '3DL1-S1', 'CD117', '2DS4', 'ILT2-CD85j', 'NKp46', 'NKG2D', 'NKG2C', '2B4', 'CD33', 'CD11b', 'NKp30', 'CD122', '3DL1', 'NKp44', 'CD127', '2DL1', 'CD94', 'CD34', 'CCR7', '2DL3', 'NKG2A', 'HLA-DR', '2DL4', 'CD56', '2DL5', 'CD25', 'DNA1', 'DNA2']


In [16]:
# select the relevant markers for further analysis
markers = ['CD3', 'CD27', 'CD19', 'CD4', 'CD8', 'CD57', '2DL1-S1', 'TRAIL', '2DL2-L3-S2', 'CD16', 'CD10', '3DL1-S1',
          'CD117', '2DS4', 'ILT2-CD85j', 'NKp46', 'NKG2D', 'NKG2C', '2B4', 'CD33', 'CD11b', 'NKp30', 'CD122', '3DL1',
          'NKp44', 'CD127', '2DL1', 'CD94', 'CD34', 'CCR7', '2DL3', 'NKG2A', 'HLA-DR', '2DL4', 'CD56', '2DL5', 'CD25']
marker_idx = [data_fcs.channels.index(label) for label in markers]
nmark = len(markers)

In [2]:
# the following function randomly split the fcs files into training and test set
# the argument `nrep` defines how many random splits to create

def create_symlinks(nrep=1):

    # prior CMV infection status obtained from ... 
    sample_ids = np.sort([f.split('_')[-2] for f in glob.glob(FCS_DATA_PATH + '/*fcs')])
    y_label = np.asarray([1,1,0,0,1,0, 1,0,0,0,1, 0,0,0,0,0, 1,1,1,1])

    # split samples into groups
    group1 = np.where(y_label == 0)[0]
    group2 = np.where(y_label == 1)[0]
    l1, l2 = len(group1), len(group2)
    ntrain_per_class = 7
    ntest_group1 = l1 - ntrain_per_class
    ntest_group2 = l2 - ntrain_per_class

    for irep in range(nrep):
        # get the sample indices
        train_idx1 = list(np.random.choice(group1, size=ntrain_per_class, replace=False))
        test_idx1 = [i for i in group1 if i not in train_idx1]
        train_idx2 = list(np.random.choice(group2, size=ntrain_per_class, replace=False))
        test_idx2 = [i for i in group2 if i not in train_idx2]

        # create directories
        basepath = os.path.join(FCS_DATA_PATH, 'CV_run_%d' % irep)
        train_path = os.path.join(basepath, 'train')
        test_path = os.path.join(basepath, 'test')
        mkdir_p(basepath)
        mkdir_p(train_path)
        mkdir_p(test_path)

        # store symbolic links to training and test FCS files
        for i, suffix in zip(train_idx1 + train_idx2, (['group1'] * len(train_idx1)) + (['group2'] * len(train_idx2))):
            fname = 'a_%s_alive' % sample_ids[i]
            os.symlink(os.path.join(FCS_DATA_PATH, fname + '.fcs'),
                    os.path.join(train_path, fname + '_%s.fcs' % suffix))
           

        for i, suffix in zip(test_idx1 + test_idx2, (['group1'] * len(test_idx1)) + (['group2'] * len(test_idx2))):
            fname = 'a_%s_alive' % sample_ids[i]
            os.symlink(os.path.join(FCS_DATA_PATH, fname + '.fcs'),
                    os.path.join(test_path, fname + '_%s.fcs' % suffix))

In [12]:
# set random seed for reproducible results
np.random.seed(12345)

# run this only once to create the training and test directories
create_symlinks()

In [17]:

cofactor = 5
i_run = 0
curr_data_dir = os.path.join(FCS_DATA_PATH, 'CV_run_%s' % i_run)
curr_out_dir = os.path.join(OUTDIR, 'CV_run_%s' % i_run)
mkdir_p(curr_out_dir)

# read the training sample names
group1 = glob.glob(curr_data_dir + '/train/*_group1.fcs')
group2 = glob.glob(curr_data_dir + '/train/*_group2.fcs')

# load the training samples
group1_list, group2_list = [], []
for fname in group1:
    x_full = np.asarray(fcm.loadFCS(fname, transform=None, auto_comp=False))
    x = ftrans(x_full[:,marker_idx], cofactor)
    group1_list.append(x)

for fname in group2:
    x_full = np.asarray(fcm.loadFCS(fname, transform=None, auto_comp=False))
    x = ftrans(x_full[:,marker_idx], cofactor)
    group2_list.append(x)

# read the test sample names
test_group1 = glob.glob(curr_data_dir + '/test/*_group1.fcs')
test_group2 = glob.glob(curr_data_dir + '/test/*_group2.fcs')

# load the test samples
t_group1_list, t_group2_list = [], []
test_phenotypes = []
for fname in test_group1:
    x_full = np.asarray(fcm.loadFCS(fname, transform=None, auto_comp=False))
    x = ftrans(x_full[:,marker_idx], cofactor)
    t_group1_list.append(x)
    test_phenotypes.append(0)

for fname in test_group2:
    x_full = np.asarray(fcm.loadFCS(fname, transform=None, auto_comp=False))
    x = ftrans(x_full[:,marker_idx], cofactor)
    t_group2_list.append(x)
    test_phenotypes.append(1)

# finally prepare training and vallidation data
cut = int(.8 * len(group1_list))
train_samples = group1_list[:cut] + group2_list[:cut]
train_phenotypes = [0] * len(group1_list[:cut]) + [1] * len(group2_list[:cut])
valid_samples = group1_list[cut:] + group2_list[cut:]
valid_phenotypes = [0] * len(group1_list[cut:]) + [1] * len(group2_list[cut:])
test_samples = t_group1_list + t_group2_list


In [18]:
# run a CellCnn analysis

model = CellCnn(ncell=3000, nsubset=1000, max_epochs=20, nrun=10, coeff_l2=0.001,
                ncell_pooled=range(10, 30), nfilter_choice=[5,10], dropout=True)

model.fit(train_samples=train_samples, train_phenotypes=train_phenotypes, labels=markers,
        valid_samples=valid_samples, valid_phenotypes=valid_phenotypes, outdir=curr_out_dir)


Generating multi-cell inputs...
Done.
training network: 1
Number of filters: 5
Cells pooled: 14
Train on 2000 samples, validate on 2000 samples
Epoch 1/20
2000/2000 [==============================] - 10s - loss: 0.6921 - acc: 0.4920 - val_loss: 0.6868 - val_acc: 0.5000
Epoch 2/20
2000/2000 [============

In [21]:
# now make predictions using the trained model
train_pred = model.predict(train_samples)
valid_pred = model.predict(valid_samples)
test_pred = model.predict(test_samples)
print train_pred, train_phenotypes
print valid_pred, valid_phenotypes
print test_pred, test_phenotypes

# calculate area under the ROC curve
train_auc = roc_auc_score(train_phenotypes, train_pred[:,1])
valid_auc = roc_auc_score(valid_phenotypes, valid_pred[:,1])
test_auc = roc_auc_score(test_phenotypes, test_pred[:,1])
print train_auc, valid_auc, test_auc

Predictions based on multi-cell inputs containing 82324 cells.
Predictions based on multi-cell inputs containing 180167 cells.
Predictions based on multi-cell inputs containing 90075 cells.
[[ 0.50745625  0.49254377]
 [ 0.59055817  0.40944184]
 [ 0.57421482  0.42578518]
 [ 0.57082629  0.4291737 ]
 [ 0.60452946  0.39547055]
 [ 0.48144838  0.51855161]
 [ 0.34044887  0.65955112]
 [ 0.36587608  0.63412392]
 [ 0.41138966  0.58861035]
 [ 0.44814619  0.5518538 ]] [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
[[ 0.58646015  0.41353987]
 [ 0.56149838  0.4385016 ]
 [ 0.39796662  0.60203338]
 [ 0.38679455  0.61320545]] [0, 0, 1, 1]
[[ 0.51673568  0.48326433]
 [ 0.60288324  0.39711676]
 [ 0.53964974  0.46035027]
 [ 0.45359471  0.5464053 ]
 [ 0.41378783  0.5862122 ]
 [ 0.49041462  0.50958539]] [0, 0, 0, 0, 1, 1]
1.0 1.0 0.875


In [22]:
# plot the results of the CellCnn analysis in the output directory
plot_results_2class(model.results, test_samples, test_phenotypes,
                    markers, curr_out_dir, filter_response_thres=.4, plot_tsne=False)

Loading the weights of consensus filters.
Found 1 discriminative filter(s):  [0]
